### ISSUE TITLE
readme.md

### ISSUE THREAD

**Issue by iivansic** [VedranSagodic/hellopp21#1]
readme.md nedostaje dok sve drugo si riješio svaka čast?

uglavnom odi samo u direktorij gdje su ti fajlovi i napravi s notepadom readme.md i u njega pastaj samo tocke koje si odradio tj sve od profesora jel. i sljedeći put kad pushaš na github on prepozna taj file i postavi kao kao opis tvoj applikacije jel how to use. tako sam ja odradio  možda ima bolji način ja sam ovaj probo i radilo je xD 
/sve si odradio jedino ovo bode u oči da fali a jednostavno je xD

**Comment by VedranSagodic** [comment]
Hvala ti na pregledu..izgleda da kad sam radio force push na github sa laptopa nakon što sam napravio sve izbrisao se readme.md.
